name: My First Workflow
on: [push, fork]
jobs:
  
  first_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -alht

      - name: Executing Shell Script
        run: |
          chmod u+x ascii-script.sh
          ./ascii-script.sh

      - name: Upload dragon.txt file for other jobs
        uses: actions/upload-artifact@v4.5.0
        with:
          name: dragon-text-file
          path: dragon.txt

  # each job runs in its own vm
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:

      - name: Download dragon.txt file for other jobs
        uses: actions/download-artifact@v4.1.8
        with:
          name: dragon-text-file

      - name: Sleep for 10 seconds
        run: sleep 40

      - name: Test file exists
        run: grep -i dragon dragon.txt
