name: My First Workflow
on: [push, fork]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install cowsay program
        run: sudo apt-get install -y cowsay

      - name: Welcome message
        run: |
          echo "My first GitHub Action Job"
          ls -ltra
          cat README.md

      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover" >> dragon.txt

      - name: Saved message file contains the work dragon
        run: grep -i dragon dragon.txt