name: My First Workflow
on: [push, fork]
jobs:
  
  first_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -alht

      - name: Executing Shell Script
        run: |
          chmod u+x ascii-script.sh
          ./ascii-script.sh